from enum import Enum

class TokenType(Enum):
    ATUR = "ATUR"
    JIKA = "JIKA"
    MAKA = "MAKA"
    TIDAK = "TIDAK"
    BERHASIL = "BERHASIL"
    PROSES = "PROSES"
    AMBIL = "AMBIL"
    DARI = "DARI"
    KEMBALI = "KEMBALI"
    BENAR = "BENAR"
    SALAH = "SALAH"
    SAMA_DENGAN = "="
    PLUS = "+"
    TITIK = "."
    KOMA = ","
    KURUNG_BUKA = "("
    KURUNG_TUTUP = ")"
    KURAWAL_BUKA = "{"
    KURAWAL_TUTUP = "}"
    IDENTIFIER = "IDENTIFIER"
    STRING = "STRING"
    NUMBER = "NUMBER"
    TIDAK_DIKENALI = "TIDAK_DIKENALI"
    EOF = "EOF"
